# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicalLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=120)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceLocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='geographicallocation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.PlaceLocation'),
        ),
    ]
