# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20170401_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicallocation',
            name='type',
            field=models.CharField(choices=[('Airpot', 'Airport'), ('Hospital', 'Hospital')], max_length=20),
        ),
    ]
