# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20170401_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicallocation',
            name='type',
            field=models.CharField(choices=[('airport', 'airport'), ('amusement_park', 'amusement_park'), ('aquarium', 'aquarium'), ('atm', 'atm'), ('bus_station', 'Bus Station'), ('casino', 'casino'), ('fire_station', 'fire_station'), ('gas_station', 'gas_station')], max_length=20),
        ),
    ]
