# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_auto_20170401_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
