# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_auto_20170401_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
