# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_auto_20170401_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelocation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
